rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
gemfile:
  - gemfiles/Gemfile-activemodel-3.0.x
  - gemfiles/Gemfile-activemodel-3.1.x
  - gemfiles/Gemfile-activemodel-3.2.x
  - gemfiles/Gemfile-activemodel-4.0.x
  - gemfiles/Gemfile-activemodel-4.1.x
  - gemfiles/Gemfile-activemodel-4.2.x
  - gemfiles/Gemfile-activemodel-5.0.x
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile-activemodel-5.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-activemodel-5.0.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile-activemodel-5.0.x
sudo: false
